[package]
name = "rlfsc"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
bytes = "0.4.11"
num = "0.2"
tokio = "0.1.15"
ux = "0.1"
